// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrafficVision.Infrastructure.Data.Persistence;

#nullable disable

namespace TrafficVision.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251122001310_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrafficVision.Domain.Entities.ReportRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("registro_relatorio", (string)null);
                });

            modelBuilder.Entity("TrafficVision.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(110)
                        .HasColumnType("character varying(110)")
                        .HasColumnName("nome");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer")
                        .HasColumnName("cargo");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("TrafficVision.Domain.Entities.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cor");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.HasKey("Id");

                    b.ToTable("veiculo", (string)null);
                });

            modelBuilder.Entity("TrafficVision.Domain.Entities.ReportRegistration", b =>
                {
                    b.HasOne("TrafficVision.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrafficVision.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TrafficVision.Domain.Entities.User", b =>
                {
                    b.OwnsOne("TrafficVision.Domain.Entities.UserEmail", "UserEmail", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("TrafficVision.Domain.Entities.UserPassword", "UserPassword", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("senha");

                            b1.HasKey("UserId");

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("UserEmail")
                        .IsRequired();

                    b.Navigation("UserPassword")
                        .IsRequired();
                });

            modelBuilder.Entity("TrafficVision.Domain.Entities.Vehicle", b =>
                {
                    b.OwnsOne("TrafficVision.Domain.Entities.VehicleSpec", "VehicleSpec", b1 =>
                        {
                            b1.Property<long>("VehicleId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Chassis")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("chassis");

                            b1.Property<int>("DataVehicleCondition")
                                .HasColumnType("integer")
                                .HasColumnName("condicao_dados_veiculo");

                            b1.Property<int>("EnumTypeFuelVehicle")
                                .HasColumnType("integer")
                                .HasColumnName("tipo_combustivel");

                            b1.Property<string>("Municipality")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("municipio");

                            b1.Property<string>("Plate")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("placa");

                            b1.Property<string>("Renavam")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("renavam");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("estado");

                            b1.HasKey("VehicleId");

                            b1.ToTable("veiculo");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");

                            b1.OwnsOne("TrafficVision.Domain.Entities.VehicleOwner", "Owner", b2 =>
                                {
                                    b2.Property<long>("VehicleSpecVehicleId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Cnh")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("cnh_dono");

                                    b2.Property<string>("CpfCnpj")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("cpf_cnpj_dono");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("nome_dono");

                                    b2.HasKey("VehicleSpecVehicleId");

                                    b2.ToTable("veiculo");

                                    b2.WithOwner()
                                        .HasForeignKey("VehicleSpecVehicleId");
                                });

                            b1.OwnsOne("TrafficVision.Domain.Entities.VehicleRestriction", "VehicleRestriction", b2 =>
                                {
                                    b2.Property<long>("VehicleSpecVehicleId")
                                        .HasColumnType("bigint");

                                    b2.Property<bool>("Auction")
                                        .HasColumnType("boolean")
                                        .HasColumnName("leiloado");

                                    b2.Property<bool>("JudicialRestriction")
                                        .HasColumnType("boolean")
                                        .HasColumnName("restricao_judicial");

                                    b2.Property<int>("TheftVehicleCondition")
                                        .HasColumnType("integer")
                                        .HasColumnName("condicao_crime");

                                    b2.Property<bool>("Wrecked")
                                        .HasColumnType("boolean")
                                        .HasColumnName("sinistrado");

                                    b2.HasKey("VehicleSpecVehicleId");

                                    b2.ToTable("veiculo");

                                    b2.WithOwner()
                                        .HasForeignKey("VehicleSpecVehicleId");
                                });

                            b1.Navigation("Owner")
                                .IsRequired();

                            b1.Navigation("VehicleRestriction")
                                .IsRequired();
                        });

                    b.Navigation("VehicleSpec")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
