<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.1.0" />
		<PackageReference Include="MediatR" Version="13.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TrafficVision.Domain\TrafficVision.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Features\Commands\DynamicReport\Update\" />
	</ItemGroup>

</Project>
